export const ProductsData = {
  Electronics: [
    {
      id: 1,
      Product: "APPLE iPhone 11 (Black, 64 GB)",
      Sellingprice: "37,999",
      Orginalprice: "43,900",
      Descripition: "64 GB ROM",
      Display: "15.49 cm (6.1 inch) Liquid Retina HD Display",
      Camera: "12MP + 12MP | 12MP Front Camera",
      Battery: "  ",
      Proccessor: "Brand Warranty of 1 Year",
      url: "https://rukminim1.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/x/j/s/iphone-11-128-d-mwm02hn-a-apple-0-original-imafkg242ugz8hwc.jpeg?q=70",
      rating: 4.5,
      reviews: 20000,
    },
    {
      id: 2,
      Product: "APPLE iPhone 11 (White, 64 GB)",
      Sellingprice: "37,999",
      Orginalprice: "43,990",
      Descripition: "64 GB ROM",
      Display: "15.49 cm (6.1 inch) Liquid Retina HD Display",
      Camera: "12MP + 12MP | 12MP Front Camera",
      Battery: "A13 Bionic Chip Processor",
      Proccessor: "Brand Warranty of 1 Year",
      url: "https://rukminim1.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/k/y/d/iphone-11-256-u-mwm82hn-a-apple-0-original-imafkg25mhaztxns.jpeg?q=70",
      rating: 4.5,
      reviews: 20001,
    },
    {
      id: 3,
      Product: "SAMSUNG Galaxy F22 (Denim Blue, 64 GB)",
      Sellingprice: "10,499",
      Orginalprice: "14,999",
      Descripition: "4 GB RAM | 64 GB ROM | Expandable Upto 1 TB",
      Display: "16.26 cm (6.4 inch) HD+ Display",
      Camera: "48MP + 8MP + 2MP + 2MP | 13MP Front Camera",
      Battery: "6000 mAh Lithium-ion Battery",
      Proccessor: "MediaTek Helio G80 Processor",
      url: "https://rukminim1.flixcart.com/image/312/312/kqqykcw0/mobile/j/5/7/galaxy-f22-sm-e225flbdins-samsung-original-imag4z99fp4qdfby.jpeg?q=70",
      rating: 4.5,
      reviews: 20002,
    },
    {
      id: 4,
      Product: "SAMSUNG Galaxy F22 (Denim Blue, 128 GB)",
      Sellingprice: "12,499",
      Orginalprice: "16,999",
      Descripition: "6 GB RAM | 128 GB ROM | Expandable Upto 1 TB",
      Display: "16.26 cm (6.4 inch) HD+ Display",
      Camera: "48MP + 8MP + 2MP + 2MP | 13MP Front Camera",
      Battery: "6000 mAh Lithium-ion Battery",
      Proccessor: "MediaTek Helio G80 Processor",
      url: "https://rukminim1.flixcart.com/image/312/312/kqqykcw0/mobile/j/5/7/galaxy-f22-sm-e225flbdins-samsung-original-imag4z99fp4qdfby.jpeg?q=70",
      rating: 4.5,
      reviews: 20003,
    },
    {
      id: 5,
      Product: "SAMSUNG Galaxy F22 (Denim Black, 128 GB)",
      Sellingprice: "12,499",
      Orginalprice: "16,999",
      Descripition: "6 GB RAM | 128 GB ROM | Expandable Upto 1 TB",
      Display: "16.26 cm (6.4 inch) HD+ Display",
      Camera: "48MP + 8MP + 2MP + 2MP | 13MP Front Camera",
      Battery: "6000 mAh Lithium-ion Battery",
      Proccessor: "MediaTek Helio G80 Processor",
      url: "https://rukminim1.flixcart.com/image/312/312/kqqykcw0/mobile/p/y/u/galaxy-f22-sm-e225fzkhins-samsung-original-imag4z99fagskjxd.jpeg?q=70",
      rating: 4.5,
      reviews: 20004,
    },
    {
      id: 6,
      Product: "Sony Bravia 43 inch 4K Ultra HD Smart LED TV",
      Sellingprice: "45,999",
      Orginalprice: "55,999",
      Description: "4K Ultra HD (3840 x 2160) Resolution, Android TV",
      Display: "43 inches",
      Battery: "N/A",
      Processor: "X1 4K Processor",
      url: "https://rukminim1.flixcart.com/image/312/312/kjvrdzk0/television/r/g/y/sony-kd-43x7002g-original-imafxgdgudcgeggv.jpeg?q=70",
      rating: 4.6,
      reviews: 10000,
    },
    {
      id: 7,
      Product: "Dell Inspiron 15 3000 Laptop (Intel Core i5, 8GB RAM, 1TB HDD)",
      Sellingprice: "52,999",
      Orginalprice: "65,000",
      Description: "15.6 inch Full HD Display, Intel Core i5 10th Gen",
      Display: "15.6 inches",
      Battery: "3-Cell Li-ion Battery",
      Processor: "Intel Core i5 10th Gen",
      url: "https://rukminim1.flixcart.com/image/312/312/k5cs87k0/computer/s/w/v/dell-na-laptop-original-imaf6mhtgdfkj6b3.jpeg?q=70",
      rating: 4.4,
      reviews: 5000,
    },
    {
      id: 8,
      Product: "HP DeskJet 2331 All-in-One Inkjet Printer",
      Sellingprice: "3,599",
      Orginalprice: "5,499",
      Description: "Print, Scan, Copy - Ideal for home printing",
      Display: "N/A",
      Battery: "N/A",
      Processor: "N/A",
      url: "https://rukminim1.flixcart.com/image/312/312/kex5ci80/printer/u/n/h/hp-deskjet-2331-original-imafvhg34e8pgwdm.jpeg?q=70",
      rating: 4.3,
      reviews: 8000,
    },
    {
      id: 9,
      Product: "Logitech MK270 Wireless Keyboard and Mouse Combo",
      Sellingprice: "1,799",
      Orginalprice: "2,499",
      Description: "Wireless keyboard and mouse, 2.4GHz connection",
      Display: "N/A",
      Battery: "Up to 24 months for the keyboard, 12 months for the mouse",
      Processor: "N/A",
      url: "https://rukminim1.flixcart.com/image/312/312/k3xcdjk0/keyboard/h/g/m/logitech-mk270-original-imafn2egvufypjzr.jpeg?q=70",
      rating: 4.5,
      reviews: 15000,
    },
    {
      id: 10,
      Product: "Canon EOS 1500D DSLR Camera (18-55mm Lens)",
      Sellingprice: "29,999",
      Orginalprice: "37,999",
      Description: "24.1 MP DSLR, Full HD Recording",
      Display: "3 inches",
      Battery: "Rechargeable Li-ion Battery",
      Processor: "DIGIC 4+ Image Processor",
      url: "https://rukminim1.flixcart.com/image/312/312/jmz7csw0/dslr-camera/r/h/f/eos-1500d-eos-1500d-digital-slr-camera-canon-original-imaf9gf6ekmhaxkx.jpeg?q=70",
      rating: 4.7,
      reviews: 2500,
    },
    {
      id: 11,
      Product: "Samsung 253L Frost Free Double Door Refrigerator",
      Sellingprice: "23,999",
      Orginalprice: "27,999",
      Description: "Frost Free, Digital Inverter Technology",
      Display: "N/A",
      Battery: "N/A",
      Processor: "Digital Inverter Compressor",
      url: "https://rukminim1.flixcart.com/image/312/312/kst9gnk0/refrigerator-new/g/h/n/rt28t3483s8-hl-2-2021-samsung-original-imag6yshdwpvdnmh.jpeg?q=70",
      rating: 4.4,
      reviews: 6000,
    },
    {
      id: 12,
      Product: "Philips Air Fryer HD9252/90",
      Sellingprice: "9,999",
      Orginalprice: "12,499",
      Description: "Rapid Air Technology for health-conscious cooking",
      Display: "N/A",
      Battery: "N/A",
      Processor: "N/A",
      url: "https://rukminim1.flixcart.com/image/312/312/koixwnk0/air-fryer/i/9/f/hd9252-90-1425-800-philips-original-imag2npzhrmkjssg.jpeg?q=70",
      rating: 4.6,
      reviews: 3500,
    },
    {
      id: 13,
      Product: "Bose QuietComfort 35 II Wireless Bluetooth Headphones",
      Sellingprice: "22,999",
      Orginalprice: "29,999",
      Description: "Active noise cancellation, Alexa-enabled",
      Display: "N/A",
      Battery: "Up to 20 hours of wireless listening",
      Processor: "N/A",
      url: "https://rukminim1.flixcart.com/image/312/312/jmz7ki80/headphone/q/c/9/bose-quietcomfort-35-ii-original-imaf9g8ghyxhtazh.jpeg?q=70",
      rating: 4.7,
      reviews: 5000,
    },
    {
      id: 14,
      Product: "Mi LED Smart TV 4A PRO 32 inches",
      Sellingprice: "15,499",
      Orginalprice: "19,999",
      Description: "HD Ready Smart TV, 20W Speakers, PatchWall OS",
      Display: "32 inches",
      Battery: "N/A",
      Processor: "Quad-core Processor",
      url: "https://rukminim1.flixcart.com/image/312/312/k8ro3gw0/television/a/h/n/mi-l32m5-al-original-imafqega7jzysgza.jpeg?q=70",
      rating: 4.4,
      reviews: 12000,
    },
    {
      id: 15,
      Product: "Asus ROG Strix G15 Gaming Laptop (AMD Ryzen 7, 16GB RAM, 512GB SSD)",
      Sellingprice: "95,999",
      Orginalprice: "1,12,999",
      Description: "15.6 inch Full HD Display, NVIDIA GTX 1650 Ti",
      Display: "15.6 inches",
      Battery: "4-Cell Li-ion Battery",
      Processor: "AMD Ryzen 7",
      url: "https://rukminim1.flixcart.com/image/312/312/kox8b680/computer/m/6/c/rog-strix-g15-g513ih-hn084t-gaming-laptop-asus-original-imag39vhfzssmepm.jpeg?q=70",
      rating: 4.7,
      reviews: 2000,
    },
    {
      id: 16,
      Product: "MOTOROLA e40 (Carbon Gray, 64 GB)",
      Sellingprice: "8,599",
      Orginalprice: "10,999",
      Descripition: "4 GB RAM | 64 GB ROM | Expandable Upto 1 TB",
      Display: "16.51 cm (6.5 inch) HD+ Display",
      Camera: "48MP + 2MP + 2MP | 8MP Front Camera",
      Battery: "5000 mAh Battery",
      Proccessor: "UNISOC T700 Processor",
      url: "https://rukminim1.flixcart.com/image/312/312/l1l1rww0/mobile/v/7/n/-original-imagd48zkjwujxzz.jpeg?q=70",
      rating: 4.5,
      reviews: 20015,
    },
    {
      id: 17,
      Product: "APPLE iPhone 11 (Purple, 64 GB)",
      Sellingprice: "37,999",
      Orginalprice: "43,900",
      Descripition: "64 GB ROM",
      Display: "15.49 cm (6.1 inch) Liquid Retina HD Display",
      Camera: "12MP + 12MP | 12MP Front Camera",
      Battery: "A13 Bionic Chip Processor",
      Proccessor: "Brand Warranty of 1 Year",
      url: "https://rukminim1.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/y/k/z/iphone-11-64-a-mwlx2hn-a-apple-0-original-imafkg24ymsjav9h.jpeg?q=70",
      rating: 4.5,
      reviews: 20016,
    },
    {
      id: 18,
      Product: "MOTOROLA e40 (Pink Clay, 64 GB)",
      Sellingprice: "8,599",
      Orginalprice: "10,999",
      Descripition: "4 GB RAM | 64 GB ROM | Expandable Upto 1 TB",
      Display: "16.51 cm (6.5 inch) HD+ Display",
      Camera: "48MP + 2MP + 2MP | 8MP Front Camera",
      Battery: "5000 mAh Battery",
      Proccessor: "UNISOC T700 Processor",
      url: "https://rukminim1.flixcart.com/image/312/312/l1l1rww0/mobile/v/7/n/-original-imagd48zkjwujxzz.jpeg?q=70",
      rating: 4.5,
      reviews: 20017,
    },
    {
      id: 19,
      Product: "APPLE iPhone 13 (Blue, 128 GB)",
      Sellingprice: "62,999",
      Orginalprice: "69,900",
      Descripition: "128 GB ROM",
      Display: "15.49 cm (6.1 inch) Super Retina XDR Display",
      Camera: "12MP + 12MP | 12MP Front Camera",
      Battery: "A15 Bionic Chip Processor",
      Proccessor: "Brand Warranty for 1 Year",
      url: "https://rukminim1.flixcart.com/image/312/312/ktketu80/mobile/2/y/o/iphone-13-mlpk3hn-a-apple-original-imag6vpyur6hjngg.jpeg?q=70",
      rating: 4.5,
      reviews: 20018,
    },
    {
      id: 20,
      Product: "vivo T1X (Space Blue, 64 GB)",
      Sellingprice: "11,999",
      Orginalprice: "16,990",
      Descripition: "4 GB RAM | 64 GB ROM",
      Display: "16.71 cm (6.58 inch) Full HD+ Display",
      Camera: "50MP + 2MP | 8MP Front Camera",
      Battery: "5000 mAh Battery",
      Proccessor: "Qualcomm Snapdragon 680 Processor",
      url: "https://rukminim1.flixcart.com/image/312/312/xif0q/mobile/8/a/y/-original-imaggbtszycsgjp5.jpeg?q=70",
      rating: 4.5,
      reviews: 20019,
    },
  ],
  Clothings: [
    {
      id: 1,
      Product: "Women's Casual Summer Dress",
      Sellingprice: "1,299",
      Orginalprice: "1,799",
      Description: "Cotton | Floral Print | Sleeveless",
      Size: "S, M, L, XL",
      Material: "100% Cotton",
      Color: "Blue",
      url: "https://example.com/image1.jpg",
      rating: 4.3,
      reviews: 1050,
    },
    {
      id: 2,
      Product: "Men's Formal Shirt",
      Sellingprice: "999",
      Orginalprice: "1,299",
      Description: "Polyester | Full Sleeve",
      Size: "M, L, XL, XXL",
      Material: "Polyester",
      Color: "White",
      url: "https://example.com/image2.jpg",
      rating: 4.1,
      reviews: 840,
    },
    {
      id: 3,
      Product: "Women's Party Wear Gown",
      Sellingprice: "2,499",
      Orginalprice: "3,499",
      Description: "Georgette | Embroidered | Full Length",
      Size: "S, M, L, XL",
      Material: "Georgette",
      Color: "Red",
      url: "https://example.com/image3.jpg",
      rating: 4.7,
      reviews: 520,
    },
    {
      id: 4,
      Product: "Men's Casual Denim Jacket",
      Sellingprice: "1,899",
      Orginalprice: "2,499",
      Description: "Denim | Slim Fit | Full Sleeve",
      Size: "M, L, XL",
      Material: "Denim",
      Color: "Black",
      url: "https://example.com/image4.jpg",
      rating: 4.2,
      reviews: 1300,
    },
    {
      id: 5,
      Product: "Women's A-line Skirt",
      Sellingprice: "799",
      Orginalprice: "1,099",
      Description: "Cotton | Knee Length",
      Size: "S, M, L, XL",
      Material: "Cotton",
      Color: "Pink",
      url: "https://example.com/image5.jpg",
      rating: 4.0,
      reviews: 620,
    },
    {
      id: 6,
      Product: "Men's Polo T-shirt",
      Sellingprice: "599",
      Orginalprice: "899",
      Description: "Cotton | Half Sleeve",
      Size: "M, L, XL, XXL",
      Material: "Cotton",
      Color: "Navy Blue",
      url: "https://example.com/image6.jpg",
      rating: 4.3,
      reviews: 1100,
    },
    {
      id: 7,
      Product: "Women's Maxi Dress",
      Sellingprice: "1,599",
      Orginalprice: "2,199",
      Description: "Silk Blend | Floor Length",
      Size: "S, M, L",
      Material: "Silk Blend",
      Color: "Green",
      url: "https://example.com/image7.jpg",
      rating: 4.8,
      reviews: 300,
    },
    {
      id: 8,
      Product: "Men's Chinos Pants",
      Sellingprice: "1,099",
      Orginalprice: "1,599",
      Description: "Cotton | Slim Fit",
      Size: "30, 32, 34, 36",
      Material: "Cotton",
      Color: "Beige",
      url: "https://example.com/image8.jpg",
      rating: 4.4,
      reviews: 710,
    },
    {
      id: 9,
      Product: "Women's Ethnic Kurta",
      Sellingprice: "899",
      Orginalprice: "1,199",
      Description: "Rayon | 3/4 Sleeve",
      Size: "S, M, L, XL",
      Material: "Rayon",
      Color: "Yellow",
      url: "https://example.com/image9.jpg",
      rating: 4.1,
      reviews: 1020,
    },
    {
      id: 10,
      Product: "Men's Leather Jacket",
      Sellingprice: "3,999",
      Orginalprice: "4,999",
      Description: "Leather | Slim Fit | Full Sleeve",
      Size: "M, L, XL",
      Material: "Leather",
      Color: "Brown",
      url: "https://example.com/image10.jpg",
      rating: 4.6,
      reviews: 500,
    },
    {
      id: 11,
      Product: "Women's Workout Leggings",
      Sellingprice: "499",
      Orginalprice: "799",
      Description: "Polyester Blend | Stretchable",
      Size: "S, M, L, XL",
      Material: "Polyester Blend",
      Color: "Black",
      url: "https://example.com/image11.jpg",
      rating: 4.5,
      reviews: 950,
    },
    {
      id: 12,
      Product: "Men's Tracksuit",
      Sellingprice: "1,599",
      Orginalprice: "2,099",
      Description: "Polyester | Full Sleeve",
      Size: "M, L, XL, XXL",
      Material: "Polyester",
      Color: "Grey",
      url: "https://example.com/image12.jpg",
      rating: 4.2,
      reviews: 780,
    },
    {
      id: 13,
      Product: "Women's Boho Tunic",
      Sellingprice: "1,199",
      Orginalprice: "1,599",
      Description: "Chiffon | 3/4 Sleeve",
      Size: "S, M, L",
      Material: "Chiffon",
      Color: "Purple",
      url: "https://example.com/image13.jpg",
      rating: 4.3,
      reviews: 610,
    },
    {
      id: 14,
      Product: "Men's Gym Shorts",
      Sellingprice: "699",
      Orginalprice: "999",
      Description: "Polyester | Slim Fit",
      Size: "M, L, XL",
      Material: "Polyester",
      Color: "Black",
      url: "https://example.com/image14.jpg",
      rating: 4.5,
      reviews: 920,
    },
    {
      id: 15,
      Product: "Women's Wrap Dress",
      Sellingprice: "1,799",
      Orginalprice: "2,399",
      Description: "Polyester | Sleeveless",
      Size: "S, M, L, XL",
      Material: "Polyester",
      Color: "Red",
      url: "https://example.com/image15.jpg",
      rating: 4.6,
      reviews: 500,
    },
    {
      id: 16,
      Product: "Men's Blazer",
      Sellingprice: "4,999",
      Orginalprice: "6,499",
      Description: "Wool Blend | Slim Fit",
      Size: "M, L, XL, XXL",
      Material: "Wool Blend",
      Color: "Navy Blue",
      url: "https://example.com/image16.jpg",
      rating: 4.7,
      reviews: 300,
    },
    {
      id: 17,
      Product: "Women's Palazzo Pants",
      Sellingprice: "899",
      Orginalprice: "1,299",
      Description: "Cotton | Wide Leg",
      Size: "S, M, L, XL",
      Material: "Cotton",
      Color: "White",
      url: "https://example.com/image17.jpg",
      rating: 4.1,
      reviews: 870,
    },
    {
      id: 18,
      Product: "Men's Hooded Sweatshirt",
      Sellingprice: "1,499",
      Orginalprice: "2,099",
      Description: "Fleece | Full Sleeve",
      Size: "M, L, XL, XXL",
      Material: "Fleece",
      Color: "Grey",
      url: "https://example.com/image18.jpg",
      rating: 4.4,
      reviews: 750,
    },
    {
      id: 19,
      Product: "Women's Crop Top",
      Sellingprice: "599",
      Orginalprice: "899",
      Description: "Cotton | Sleeveless",
      Size: "S, M, L",
      Material: "Cotton",
      Color: "Black",
      url: "https://example.com/image19.jpg",
      rating: 4.3,
      reviews: 1200,
    },
    {
      id: 20,
      Product: "Men's Cargo Pants",
      Sellingprice: "1,199",
      Orginalprice: "1,799",
      Description: "Cotton | Relaxed Fit",
      Size: "30, 32, 34, 36",
      Material: "Cotton",
      Color: "Olive Green",
      url: "https://example.com/image20.jpg",
      rating: 4.2,
      reviews: 890,
    },
  ],
  BeautyProducts: [
    {
      id: 1,
      Product: "Moisturizing Face Cream",
      Sellingprice: "499",
      Orginalprice: "699",
      Description: "Hydrating face cream with Vitamin E",
      Size: "50ml",
      Ingredients: "Aloe Vera, Vitamin E, Shea Butter",
      SkinType: "All Skin Types",
      url: "https://example.com/image1.jpg",
      rating: 4.6,
      reviews: 1250,
    },
    {
      id: 2,
      Product: "Liquid Foundation",
      Sellingprice: "1,199",
      Orginalprice: "1,499",
      Description: "Full coverage matte foundation",
      Size: "30ml",
      Ingredients: "Water, Glycerin, Silica",
      SkinType: "Oily Skin",
      url: "https://example.com/image2.jpg",
      rating: 4.4,
      reviews: 980,
    },
    {
      id: 3,
      Product: "Waterproof Mascara",
      Sellingprice: "799",
      Orginalprice: "999",
      Description: "Volumizing waterproof mascara",
      Size: "10ml",
      Ingredients: "Beeswax, Black Iron Oxide",
      SkinType: "All Skin Types",
      url: "https://example.com/image3.jpg",
      rating: 4.7,
      reviews: 1620,
    },
    {
      id: 4,
      Product: "Nude Lipstick",
      Sellingprice: "499",
      Orginalprice: "799",
      Description: "Long-lasting matte lipstick",
      Size: "3.5g",
      Ingredients: "Cocoa Butter, Vitamin E",
      SkinType: "All Skin Types",
      url: "https://example.com/image4.jpg",
      rating: 4.5,
      reviews: 1500,
    },
    {
      id: 5,
      Product: "Charcoal Face Mask",
      Sellingprice: "399",
      Orginalprice: "599",
      Description: "Deep cleansing charcoal face mask",
      Size: "100ml",
      Ingredients: "Activated Charcoal, Clay, Aloe Vera",
      SkinType: "Oily and Combination Skin",
      url: "https://example.com/image5.jpg",
      rating: 4.3,
      reviews: 2000,
    },
    {
      id: 6,
      Product: "Makeup Remover Wipes",
      Sellingprice: "299",
      Orginalprice: "499",
      Description: "Gentle makeup remover wipes",
      Size: "30 wipes",
      Ingredients: "Aloe Vera, Chamomile, Vitamin E",
      SkinType: "All Skin Types",
      url: "https://example.com/image6.jpg",
      rating: 4.4,
      reviews: 1100,
    },
    {
      id: 7,
      Product: "Vitamin C Serum",
      Sellingprice: "899",
      Orginalprice: "1,199",
      Description: "Brightening Vitamin C serum",
      Size: "30ml",
      Ingredients: "Vitamin C, Hyaluronic Acid, Aloe Vera",
      SkinType: "All Skin Types",
      url: "https://example.com/image7.jpg",
      rating: 4.8,
      reviews: 980,
    },
    {
      id: 8,
      Product: "BB Cream",
      Sellingprice: "699",
      Orginalprice: "999",
      Description: "Lightweight BB cream with SPF 30",
      Size: "40ml",
      Ingredients: "Glycerin, Niacinamide, SPF 30",
      SkinType: "All Skin Types",
      url: "https://example.com/image8.jpg",
      rating: 4.3,
      reviews: 1200,
    },
    {
      id: 9,
      Product: "Matte Finish Setting Spray",
      Sellingprice: "599",
      Orginalprice: "799",
      Description: "Long-lasting matte setting spray",
      Size: "50ml",
      Ingredients: "Witch Hazel, Aloe Vera, Glycerin",
      SkinType: "All Skin Types",
      url: "https://example.com/image9.jpg",
      rating: 4.6,
      reviews: 870,
    },
    {
      id: 10,
      Product: "Exfoliating Face Scrub",
      Sellingprice: "349",
      Orginalprice: "499",
      Description: "Gentle exfoliating scrub with walnut",
      Size: "100ml",
      Ingredients: "Walnut, Aloe Vera, Vitamin E",
      SkinType: "All Skin Types",
      url: "https://example.com/image10.jpg",
      rating: 4.2,
      reviews: 1300,
    },
    {
      id: 11,
      Product: "Sunscreen SPF 50",
      Sellingprice: "599",
      Orginalprice: "899",
      Description: "Broad-spectrum sunscreen with SPF 50",
      Size: "75ml",
      Ingredients: "Zinc Oxide, Aloe Vera, Vitamin E",
      SkinType: "All Skin Types",
      url: "https://example.com/image11.jpg",
      rating: 4.5,
      reviews: 1500,
    },
    {
      id: 12,
      Product: "Lip Balm",
      Sellingprice: "199",
      Orginalprice: "299",
      Description: "Moisturizing lip balm with shea butter",
      Size: "4g",
      Ingredients: "Shea Butter, Beeswax, Vitamin E",
      SkinType: "All Skin Types",
      url: "https://example.com/image12.jpg",
      rating: 4.4,
      reviews: 1700,
    },
    {
      id: 13,
      Product: "Night Repair Cream",
      Sellingprice: "1,299",
      Orginalprice: "1,799",
      Description: "Anti-aging night repair cream",
      Size: "50ml",
      Ingredients: "Retinol, Hyaluronic Acid, Vitamin E",
      SkinType: "Mature Skin",
      url: "https://example.com/image13.jpg",
      rating: 4.7,
      reviews: 950,
    },
    {
      id: 14,
      Product: "Eyeliner Pen",
      Sellingprice: "399",
      Orginalprice: "599",
      Description: "Waterproof smudge-proof eyeliner",
      Size: "1.2g",
      Ingredients: "Black Iron Oxide, Beeswax",
      SkinType: "All Skin Types",
      url: "https://example.com/image14.jpg",
      rating: 4.6,
      reviews: 1400,
    },
    {
      id: 15,
      Product: "Blush Palette",
      Sellingprice: "699",
      Orginalprice: "999",
      Description: "4-color blush palette for all skin tones",
      Size: "12g",
      Ingredients: "Talc, Mica, Pigments",
      SkinType: "All Skin Types",
      url: "https://example.com/image15.jpg",
      rating: 4.4,
      reviews: 1200,
    },
    {
      id: 16,
      Product: "Anti-Frizz Hair Serum",
      Sellingprice: "499",
      Orginalprice: "699",
      Description: "Nourishing serum for frizzy hair",
      Size: "100ml",
      Ingredients: "Argan Oil, Vitamin E, Keratin",
      HairType: "Frizzy Hair",
      url: "https://example.com/image16.jpg",
      rating: 4.5,
      reviews: 850,
    },
    {
      id: 17,
      Product: "Cleansing Micellar Water",
      Sellingprice: "399",
      Orginalprice: "599",
      Description: "Gentle makeup remover and cleanser",
      Size: "200ml",
      Ingredients: "Micelles, Aloe Vera, Chamomile",
      SkinType: "All Skin Types",
      url: "https://example.com/image17.jpg",
      rating: 4.6,
      reviews: 1800,
    },
    {
      id: 18,
      Product: "Nail Polish Set",
      Sellingprice: "599",
      Orginalprice: "899",
      Description: "Set of 5 glossy nail polishes",
      Size: "5x10ml",
      Ingredients: "Toluene, Ethyl Acetate, Pigments",
      SkinType: "All Skin Types",
      url: "https://example.com/image18.jpg",
      rating: 4.3,
      reviews: 760,
    },
    {
      id: 19,
      Product: "Eyebrow Pencil",
      Sellingprice: "299",
      Orginalprice: "499",
      Description: "Precision eyebrow pencil",
      Size: "1.5g",
      Ingredients: "Beeswax, Castor Oil, Black Iron Oxide",
      SkinType: "All Skin Types",
      url: "https://example.com/image19.jpg",
      rating: 4.4,
      reviews: 1400,
    },
    {
      id: 20,
      Product: "Brightening Face Wash",
      Sellingprice: "349",
      Orginalprice: "499",
      Description: "Gentle brightening face wash with Vitamin C",
      Size: "100ml",
      Ingredients: "Vitamin C, Aloe Vera, Glycerin",
      SkinType: "All Skin Types",
      url: "https://example.com/image20.jpg",
      rating: 4.2,
      reviews: 1800,
    },
  ],
  Grocery: [
    {
      id: 1,
      Product: "Basmati Rice",
      Sellingprice: "499",
      Orginalprice: "599",
      Description: "Premium long-grain basmati rice",
      Size: "5kg",
      Ingredients: "Basmati Rice",
      url: "https://example.com/image1.jpg",
      rating: 4.6,
      reviews: 1250,
    },
    {
      id: 2,
      Product: "Olive Oil",
      Sellingprice: "999",
      Orginalprice: "1,199",
      Description: "Extra virgin cold-pressed olive oil",
      Size: "1L",
      Ingredients: "100% Olive Oil",
      url: "https://example.com/image2.jpg",
      rating: 4.5,
      reviews: 980,
    },
    {
      id: 3,
      Product: "Organic Wheat Flour",
      Sellingprice: "299",
      Orginalprice: "399",
      Description: "Whole wheat flour, organic",
      Size: "2kg",
      Ingredients: "Whole Wheat",
      url: "https://example.com/image3.jpg",
      rating: 4.4,
      reviews: 1500,
    },
    {
      id: 4,
      Product: "Almonds",
      Sellingprice: "799",
      Orginalprice: "999",
      Description: "Premium California almonds",
      Size: "500g",
      Ingredients: "Almonds",
      url: "https://example.com/image4.jpg",
      rating: 4.7,
      reviews: 1620,
    },
    {
      id: 5,
      Product: "Coconut Sugar",
      Sellingprice: "349",
      Orginalprice: "499",
      Description: "Natural coconut sugar",
      Size: "500g",
      Ingredients: "Coconut Sap",
      url: "https://example.com/image5.jpg",
      rating: 4.3,
      reviews: 1400,
    },
    {
      id: 6,
      Product: "Quinoa",
      Sellingprice: "449",
      Orginalprice: "599",
      Description: "Organic white quinoa",
      Size: "1kg",
      Ingredients: "Quinoa",
      url: "https://example.com/image6.jpg",
      rating: 4.5,
      reviews: 1000,
    },
    {
      id: 7,
      Product: "Green Tea",
      Sellingprice: "199",
      Orginalprice: "299",
      Description: "Organic loose-leaf green tea",
      Size: "100g",
      Ingredients: "Green Tea",
      url: "https://example.com/image7.jpg",
      rating: 4.8,
      reviews: 780,
    },
    {
      id: 8,
      Product: "Chia Seeds",
      Sellingprice: "349",
      Orginalprice: "499",
      Description: "Rich in omega-3 and fiber",
      Size: "500g",
      Ingredients: "Chia Seeds",
      url: "https://example.com/image8.jpg",
      rating: 4.6,
      reviews: 880,
    },
    {
      id: 9,
      Product: "Honey",
      Sellingprice: "599",
      Orginalprice: "799",
      Description: "Raw organic wildflower honey",
      Size: "500g",
      Ingredients: "Honey",
      url: "https://example.com/image9.jpg",
      rating: 4.7,
      reviews: 940,
    },
    {
      id: 10,
      Product: "Organic Turmeric Powder",
      Sellingprice: "199",
      Orginalprice: "299",
      Description: "Organic turmeric powder",
      Size: "200g",
      Ingredients: "Turmeric",
      url: "https://example.com/image10.jpg",
      rating: 4.5,
      reviews: 1200,
    },
    {
      id: 11,
      Product: "Brown Rice",
      Sellingprice: "499",
      Orginalprice: "599",
      Description: "Organic long-grain brown rice",
      Size: "5kg",
      Ingredients: "Brown Rice",
      url: "https://example.com/image11.jpg",
      rating: 4.4,
      reviews: 1100,
    },
    {
      id: 12,
      Product: "Coconut Oil",
      Sellingprice: "599",
      Orginalprice: "799",
      Description: "Cold-pressed virgin coconut oil",
      Size: "1L",
      Ingredients: "Coconut Oil",
      url: "https://example.com/image12.jpg",
      rating: 4.7,
      reviews: 850,
    },
    {
      id: 13,
      Product: "Cashews",
      Sellingprice: "899",
      Orginalprice: "1,199",
      Description: "Premium whole cashews",
      Size: "500g",
      Ingredients: "Cashews",
      url: "https://example.com/image13.jpg",
      rating: 4.6,
      reviews: 900,
    },
    {
      id: 14,
      Product: "Rolled Oats",
      Sellingprice: "299",
      Orginalprice: "399",
      Description: "Gluten-free rolled oats",
      Size: "1kg",
      Ingredients: "Rolled Oats",
      url: "https://example.com/image14.jpg",
      rating: 4.5,
      reviews: 1050,
    },
    {
      id: 15,
      Product: "Dark Chocolate",
      Sellingprice: "349",
      Orginalprice: "499",
      Description: "70% dark chocolate with no added sugar",
      Size: "100g",
      Ingredients: "Cocoa Mass, Cocoa Butter, Stevia",
      url: "https://example.com/image15.jpg",
      rating: 4.6,
      reviews: 950,
    },
    {
      id: 16,
      Product: "Multigrain Atta",
      Sellingprice: "299",
      Orginalprice: "399",
      Description: "Healthy multigrain wheat flour",
      Size: "2kg",
      Ingredients: "Wheat, Jowar, Ragi, Oats",
      url: "https://example.com/image16.jpg",
      rating: 4.4,
      reviews: 1250,
    },
    {
      id: 17,
      Product: "Groundnut Oil",
      Sellingprice: "699",
      Orginalprice: "899",
      Description: "Cold-pressed groundnut oil",
      Size: "1L",
      Ingredients: "Groundnut Oil",
      url: "https://example.com/image17.jpg",
      rating: 4.7,
      reviews: 790,
    },
    {
      id: 18,
      Product: "Organic Jaggery Powder",
      Sellingprice: "199",
      Orginalprice: "299",
      Description: "Unrefined organic jaggery powder",
      Size: "1kg",
      Ingredients: "Jaggery",
      url: "https://example.com/image18.jpg",
      rating: 4.6,
      reviews: 1000,
    },
    {
      id: 19,
      Product: "Sunflower Seeds",
      Sellingprice: "299",
      Orginalprice: "399",
      Description: "High-fiber sunflower seeds",
      Size: "250g",
      Ingredients: "Sunflower Seeds",
      url: "https://example.com/image19.jpg",
      rating: 4.5,
      reviews: 670,
    },
    {
      id: 20,
      Product: "Organic Almond Butter",
      Sellingprice: "699",
      Orginalprice: "899",
      Description: "Unsweetened almond butter",
      Size: "250g",
      Ingredients: "Almonds",
      url: "https://example.com/image20.jpg",
      rating: 4.7,
      reviews: 830,
    },
  ],
  Furniture: [
    {
      id: 1,
      Product: "Wooden Dining Table Set",
      Sellingprice: "19,999",
      Orginalprice: "25,999",
      Description: "6-seater solid wood dining table set with chairs",
      Material: "Sheesham Wood",
      Dimensions: "150cm x 90cm x 75cm",
      url: "https://example.com/image1.jpg",
      rating: 4.7,
      reviews: 1200,
    },
    {
      id: 2,
      Product: "Sofa Set",
      Sellingprice: "35,499",
      Orginalprice: "45,999",
      Description: "L-shaped fabric sofa set with cushions",
      Material: "Fabric, Wood",
      Dimensions: "250cm x 150cm x 85cm",
      url: "https://example.com/image2.jpg",
      rating: 4.6,
      reviews: 900,
    },
    {
      id: 3,
      Product: "King Size Bed",
      Sellingprice: "29,999",
      Orginalprice: "39,999",
      Description: "Solid wood king size bed with storage",
      Material: "Sheesham Wood",
      Dimensions: "210cm x 190cm x 100cm",
      url: "https://example.com/image3.jpg",
      rating: 4.5,
      reviews: 800,
    },
    {
      id: 4,
      Product: "Office Chair",
      Sellingprice: "4,999",
      Orginalprice: "6,999",
      Description: "Ergonomic office chair with lumbar support",
      Material: "Mesh, Plastic",
      Dimensions: "60cm x 60cm x 120cm",
      url: "https://example.com/image4.jpg",
      rating: 4.4,
      reviews: 1500,
    },
    {
      id: 5,
      Product: "TV Unit",
      Sellingprice: "12,499",
      Orginalprice: "15,999",
      Description: "Contemporary wooden TV unit with storage",
      Material: "Engineered Wood",
      Dimensions: "160cm x 45cm x 60cm",
      url: "https://example.com/image5.jpg",
      rating: 4.6,
      reviews: 1000,
    },
    {
      id: 6,
      Product: "Coffee Table",
      Sellingprice: "3,999",
      Orginalprice: "5,499",
      Description: "Modern wooden coffee table with glass top",
      Material: "Solid Wood, Glass",
      Dimensions: "100cm x 50cm x 40cm",
      url: "https://example.com/image6.jpg",
      rating: 4.3,
      reviews: 850,
    },
    {
      id: 7,
      Product: "Wardrobe",
      Sellingprice: "19,999",
      Orginalprice: "24,999",
      Description: "3-door wardrobe with mirror and drawers",
      Material: "Engineered Wood",
      Dimensions: "180cm x 60cm x 200cm",
      url: "https://example.com/image7.jpg",
      rating: 4.5,
      reviews: 1100,
    },
    {
      id: 8,
      Product: "Recliner Chair",
      Sellingprice: "17,499",
      Orginalprice: "21,999",
      Description: "Luxury recliner chair with fabric upholstery",
      Material: "Fabric, Metal",
      Dimensions: "85cm x 100cm x 105cm",
      url: "https://example.com/image8.jpg",
      rating: 4.7,
      reviews: 700,
    },
    {
      id: 9,
      Product: "Bookshelf",
      Sellingprice: "7,999",
      Orginalprice: "9,999",
      Description: "5-tier wooden bookshelf for home and office",
      Material: "Sheesham Wood",
      Dimensions: "75cm x 30cm x 180cm",
      url: "https://example.com/image9.jpg",
      rating: 4.4,
      reviews: 950,
    },
    {
      id: 10,
      Product: "Study Desk",
      Sellingprice: "5,499",
      Orginalprice: "7,499",
      Description: "Wooden study desk with drawers and storage",
      Material: "Engineered Wood",
      Dimensions: "120cm x 60cm x 75cm",
      url: "https://example.com/image10.jpg",
      rating: 4.5,
      reviews: 1200,
    },
    {
      id: 11,
      Product: "Dining Chair Set",
      Sellingprice: "6,999",
      Orginalprice: "8,999",
      Description: "Set of 4 upholstered dining chairs",
      Material: "Fabric, Wood",
      Dimensions: "45cm x 55cm x 100cm",
      url: "https://example.com/image11.jpg",
      rating: 4.3,
      reviews: 700,
    },
    {
      id: 12,
      Product: "Folding Bed",
      Sellingprice: "8,499",
      Orginalprice: "10,499",
      Description: "Single folding bed with metal frame",
      Material: "Metal, Fabric",
      Dimensions: "190cm x 90cm x 45cm",
      url: "https://example.com/image12.jpg",
      rating: 4.2,
      reviews: 650,
    },
    {
      id: 13,
      Product: "Rocking Chair",
      Sellingprice: "6,999",
      Orginalprice: "8,499",
      Description: "Classic wooden rocking chair with cushion",
      Material: "Solid Wood, Fabric",
      Dimensions: "100cm x 60cm x 110cm",
      url: "https://example.com/image13.jpg",
      rating: 4.6,
      reviews: 500,
    },
    {
      id: 14,
      Product: "Shoe Rack",
      Sellingprice: "3,499",
      Orginalprice: "4,999",
      Description: "Compact wooden shoe rack with 3 tiers",
      Material: "Engineered Wood",
      Dimensions: "75cm x 30cm x 90cm",
      url: "https://example.com/image14.jpg",
      rating: 4.4,
      reviews: 800,
    },
    {
      id: 15,
      Product: "Chest of Drawers",
      Sellingprice: "9,999",
      Orginalprice: "12,499",
      Description: "Wooden chest of 5 drawers for storage",
      Material: "Sheesham Wood",
      Dimensions: "90cm x 45cm x 120cm",
      url: "https://example.com/image15.jpg",
      rating: 4.5,
      reviews: 600,
    },
    {
      id: 16,
      Product: "Queen Size Bed",
      Sellingprice: "24,999",
      Orginalprice: "32,999",
      Description: "Wooden queen size bed with hydraulic storage",
      Material: "Solid Wood",
      Dimensions: "200cm x 160cm x 90cm",
      url: "https://example.com/image16.jpg",
      rating: 4.7,
      reviews: 750,
    },
    {
      id: 17,
      Product: "Outdoor Patio Set",
      Sellingprice: "12,499",
      Orginalprice: "16,499",
      Description: "4-piece outdoor patio set with table and chairs",
      Material: "Rattan, Metal",
      Dimensions: "Table: 75cm x 75cm x 75cm, Chair: 60cm x 60cm x 90cm",
      url: "https://example.com/image17.jpg",
      rating: 4.6,
      reviews: 500,
    },
    {
      id: 18,
      Product: "Corner Shelf",
      Sellingprice: "2,999",
      Orginalprice: "3,999",
      Description: "5-tier corner shelf for storage and decor",
      Material: "Engineered Wood",
      Dimensions: "30cm x 30cm x 150cm",
      url: "https://example.com/image18.jpg",
      rating: 4.3,
      reviews: 450,
    },
    {
      id: 19,
      Product: "Bean Bag",
      Sellingprice: "1,999",
      Orginalprice: "2,499",
      Description: "Large bean bag with washable cover",
      Material: "Leatherette",
      Dimensions: "90cm x 90cm x 120cm",
      url: "https://example.com/image19.jpg",
      rating: 4.5,
      reviews: 1200,
    },
    {
      id: 20,
      Product: "Wall Mounted Shelf",
      Sellingprice: "1,499",
      Orginalprice: "1,999",
      Description: "Decorative wall mounted shelf for books and decor",
      Material: "Engineered Wood",
      Dimensions: "100cm x 25cm x 30cm",
      url: "https://example.com/image20.jpg",
      rating: 4.4,
      reviews: 900,
    }
  ],
  Offers: [
    {
      id: 1,
      Category: "Furniture",
      Product: "Wooden Dining Table Set",
      Sellingprice: "17,999",
      Orginalprice: "25,999",
      Offer: "30% off",
      Description: "6-seater solid wood dining table set with chairs",
      Material: "Sheesham Wood",
      Dimensions: "150cm x 90cm x 75cm",
      url: "https://example.com/image1.jpg",
      rating: 4.7,
      reviews: 1200,
    },
    {
      id: 2,
      Category: "Furniture",
      Product: "Sofa Set",
      Sellingprice: "32,499",
      Orginalprice: "45,999",
      Offer: "29% off",
      Description: "L-shaped fabric sofa set with cushions",
      Material: "Fabric, Wood",
      Dimensions: "250cm x 150cm x 85cm",
      url: "https://example.com/image2.jpg",
      rating: 4.6,
      reviews: 900,
    },
    {
      id: 3,
      Category: "Electronics",
      Product: "Smart TV",
      Sellingprice: "45,999",
      Orginalprice: "55,999",
      Offer: "18% off",
      Description: "50-inch 4K UHD Smart TV with HDR",
      Size: "50 inch",
      Features: "Smart TV, 4K UHD, HDR",
      url: "https://example.com/image3.jpg",
      rating: 4.8,
      reviews: 1500,
    },
    {
      id: 4,
      Category: "Electronics",
      Product: "Bluetooth Headphones",
      Sellingprice: "2,999",
      Orginalprice: "3,999",
      Offer: "25% off",
      Description: "Wireless Bluetooth headphones with noise cancellation",
      Type: "Over-ear",
      Features: "Noise Cancellation, Wireless",
      url: "https://example.com/image4.jpg",
      rating: 4.5,
      reviews: 1200,
    },
    {
      id: 5,
      Category: "Beauty Products",
      Product: "Moisturizing Face Cream",
      Sellingprice: "399",
      Orginalprice: "499",
      Offer: "20% off",
      Description: "Rich moisturizing face cream for dry skin",
      Size: "50ml",
      Ingredients: "Hyaluronic Acid, Vitamin E",
      SkinType: "Dry Skin",
      url: "https://example.com/image5.jpg",
      rating: 4.4,
      reviews: 1300,
    },
    {
      id: 6,
      Category: "Beauty Products",
      Product: "Anti-Aging Serum",
      Sellingprice: "699",
      Orginalprice: "899",
      Offer: "22% off",
      Description: "Advanced anti-aging serum with retinol",
      Size: "30ml",
      Ingredients: "Retinol, Hyaluronic Acid",
      SkinType: "All Skin Types",
      url: "https://example.com/image6.jpg",
      rating: 4.6,
      reviews: 950,
    },
    {
      id: 7,
      Category: "Dresses and Clothing",
      Product: "Summer Dress",
      Sellingprice: "1,299",
      Orginalprice: "1,799",
      Offer: "28% off",
      Description: "Floral summer dress with a belt",
      Material: "Cotton",
      Size: "S, M, L, XL",
      url: "https://example.com/image7.jpg",
      rating: 4.5,
      reviews: 1100,
    },
    {
      id: 8,
      Category: "Dresses and Clothing",
      Product: "Men's Casual Shirt",
      Sellingprice: "899",
      Orginalprice: "1,299",
      Offer: "31% off",
      Description: "Comfortable men's casual shirt with button-down collar",
      Material: "Cotton",
      Size: "M, L, XL, XXL",
      url: "https://example.com/image8.jpg",
      rating: 4.4,
      reviews: 1000,
    },
    {
      id: 9,
      Category: "Grocery",
      Product: "Organic Olive Oil",
      Sellingprice: "899",
      Orginalprice: "1,199",
      Offer: "25% off",
      Description: "Extra virgin organic olive oil",
      Size: "500ml",
      Ingredients: "100% Olive Oil",
      url: "https://example.com/image9.jpg",
      rating: 4.6,
      reviews: 1300,
    },
    {
      id: 10,
      Category: "Grocery",
      Product: "Premium Basmati Rice",
      Sellingprice: "399",
      Orginalprice: "599",
      Offer: "33% off",
      Description: "5kg premium basmati rice",
      Size: "5kg",
      Ingredients: "Basmati Rice",
      url: "https://example.com/image10.jpg",
      rating: 4.7,
      reviews: 1150,
    },
    {
      id: 11,
      Category: "Furniture",
      Product: "King Size Bed",
      Sellingprice: "24,999",
      Orginalprice: "32,999",
      Offer: "24% off",
      Description: "Wooden king size bed with storage",
      Material: "Sheesham Wood",
      Dimensions: "210cm x 190cm x 100cm",
      url: "https://example.com/image11.jpg",
      rating: 4.5,
      reviews: 800,
    },
    {
      id: 12,
      Category: "Furniture",
      Product: "Office Chair",
      Sellingprice: "4,299",
      Orginalprice: "6,999",
      Offer: "39% off",
      Description: "Ergonomic office chair with lumbar support",
      Material: "Mesh, Plastic",
      Dimensions: "60cm x 60cm x 120cm",
      url: "https://example.com/image12.jpg",
      rating: 4.4,
      reviews: 1500,
    },
    {
      id: 13,
      Category: "Electronics",
      Product: "Smartphone",
      Sellingprice: "29,499",
      Orginalprice: "34,999",
      Offer: "15% off",
      Description: "Latest model smartphone with 128GB storage",
      Features: "5G, 128GB Storage",
      url: "https://example.com/image13.jpg",
      rating: 4.7,
      reviews: 1400,
    },
    {
      id: 14,
      Category: "Electronics",
      Product: "Smartwatch",
      Sellingprice: "8,499",
      Orginalprice: "11,999",
      Offer: "29% off",
      Description: "Smartwatch with fitness tracking and notifications",
      Features: "Fitness Tracking, Notifications",
      url: "https://example.com/image14.jpg",
      rating: 4.5,
      reviews: 1100,
    },
    {
      id: 15,
      Category: "Beauty Products",
      Product: "Hydrating Face Mist",
      Sellingprice: "249",
      Orginalprice: "399",
      Offer: "37% off",
      Description: "Refreshing hydrating face mist",
      Size: "100ml",
      Ingredients: "Rose Water, Aloe Vera, Glycerin",
      SkinType: "All Skin Types",
      url: "https://example.com/image15.jpg",
      rating: 4.5,
      reviews: 1100,
    },
    {
      id: 16,
      Category: "Beauty Products",
      Product: "Under Eye Cream",
      Sellingprice: "499",
      Orginalprice: "799",
      Offer: "38% off",
      Description: "Anti-dark circle and puffiness cream",
      Size: "20ml",
      Ingredients: "Caffeine, Hyaluronic Acid, Vitamin C",
      SkinType: "All Skin Types",
      url: "https://example.com/image16.jpg",
      rating: 4.5,
      reviews: 850,
    },
    {
      id: 17,
      Category: "Dresses and Clothing",
      Product: "Leather Jacket",
      Sellingprice: "3,999",
      Orginalprice: "5,999",
      Offer: "33% off",
      Description: "Stylish leather jacket with zip closure",
      Material: "Genuine Leather",
      Size: "S, M, L, XL",
      url: "https://example.com/image17.jpg",
      rating: 4.6,
      reviews: 950,
    },
    {
      id: 18,
      Category: "Dresses and Clothing",
      Product: "Formal Trousers",
      Sellingprice: "1,199",
      Orginalprice: "1,699",
      Offer: "29% off",
      Description: "Tailored formal trousers for men",
      Material: "Wool Blend",
      Size: "30, 32, 34, 36",
      url: "https://example.com/image18.jpg",
      rating: 4.4,
      reviews: 800,
    },
    {
      id: 19,
      Category: "Grocery",
      Product: "Chia Seeds",
      Sellingprice: "349",
      Orginalprice: "499",
      Offer: "30% off",
      Description: "Nutrient-rich chia seeds",
      Size: "200g",
      Ingredients: "Chia Seeds",
      url: "https://example.com/image19.jpg",
      rating: 4.7,
      reviews: 700,
    },
    {
      id: 20,
      Category: "Grocery",
      Product: "Almonds",
      Sellingprice: "699",
      Orginalprice: "899",
      Offer: "22% off",
      Description: "Premium quality almonds",
      Size: "250g",
      Ingredients: "Almonds",
      url: "https://example.com/image20.jpg",
      rating: 4.6,
      reviews: 800,
    }
  ]
};

